small improvements
emipa606/ProstheticDidgets pull request #1
Opened 2020-06-18 17:10 UTC by younyokel

- Added Russian language support;
- English language is separated in another folder;
- Changed "Operating on patient" to "Installing ...";
- Fxied: Bionic parts now don't appear on the Machining Table. But instead of it, they can be created only on Fabrication Bench as other bionic parts;
- Russian language improvement: Make_* added to change "Сделать" (translates to "make" or "do") to "Изготовить" (translates to "manufacture" or "fabricate"). Reason for that is because this technique is used in official russian translation and it is gramatically more correct;
- Changed every "incase" to "in case".

And also...
I tried to add "descriptionHyperlinks" tag after def's descriptions but looks like all files are located in different folders so the game can't find them... I don't know, sorry :blush:

2020-06-18 17:43 UTC, emipa606 commented on Defs/ThingDefs/Items_BodyParts.xml
> -    <description>A simple prosthetic finger incase you happen to lose one of them.. ..Or seven.</description>
Missing replacement description

2020-06-18 17:46 UTC, emipa606 requested changes
Missing replacement descriptions in Recipes_SurgeryProstheticBits.xml, Items_BodyParts.xml

About the hyperlinks, you just need to add a reference to the body-part in question. Here is the ArchotechEye from vanilla as an example:
`<defName>InstallArchotechEye</defName>
    <label>install archotech eye</label>
    <description>Install an archotech eye.</description>
    <descriptionHyperlinks><ThingDef>ArchotechEye</ThingDef></descriptionHyperlinks>`

2020-06-18 18:42 UTC, younyokel commented
> 
> 
> Missing replacement descriptions in Recipes_SurgeryProstheticBits.xml, Items_BodyParts.xml
> 
> About the hyperlinks, you just need to add a reference to the body-part in question. Here is the ArchotechEye from vanilla as an example:
> `<defName>InstallArchotechEye</defName> <label>install archotech eye</label> <description>Install an archotech eye.</description> <descriptionHyperlinks><ThingDef>ArchotechEye</ThingDef></descriptionHyperlinks>`

I also forgot to translate installed fingers and toes. About hyperlinks, it was the first thing I did but I still got no links.

2020-06-19 20:55 UTC, emipa606 approved these changes

2020-06-19 20:55 UTC, merged